apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo I am ready && sleep 3600']
      env:
        # Define the environment variable
        - name: ORANGE
          valueFrom:
            configMapKeyRef:
              name: orange
              key: slogan.txt