kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Pod al que enrutará este servicio
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80