kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  selector:
    app: guestbook # RS al que enrutará este servicio
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
